### ISSUE TITLE
Please remove the *.fifthplay.com

### ISSUE THREAD

**Issue by vitalem30** [jawz101/MobileAdTrackers#15]
Please remove from the hosts file the URL's  *.fifthplay.com which are not URL used for ads .
These links are used by company fifthplay who uses this internal communication between their system used for energymonitoring. 
So, couldyou kindly remove following link from your hosts file:
0.0.0.0 commands.fifthplay.com
0.0.0.0 poll.fifthplay.com

PS: if possible, can you tell me how our links even got there?

**Comment by jawz101** [comment]
removed.  Because someone somewhere who has their equipment uses OpenDNS and Cisco publishes a daily list of the top 1 million DNS lookups they get from their users.  I'm trying to get through and remove a lot of these sorts of entries.  I assume either the device hardcodes OpenDNS' domain servers in their devices or the company in which it's deployed uses OpenDNS.  If that was my company I'd recommend not hardcoding DNS servers in their devices if it's a privacy concern because this list is available.  If they do want one hardcoded I'd suggest [9.9.9.9](https://www.quad9.net) because it's 

this list got some information from here:
https://www.opendns.com
http://s3-us-west-1.amazonaws.com/umbrella-static/index.html

I also wouldn't use this blocklist to block ads in a corporate environment... but that's just me.
