### ISSUE TITLE
Report Tracker for Windows App

### ISSUE THREAD

**Issue by DRSDavidSoft** [jawz101/MobileAdTrackers#24]
These domains belong to [FlashGet](http://flashget.com), which is not a 'mobile' app, per se.

```
stat.flashget.com
supertracker.flashget.com
cplog.flashget.com
```

Since it's a Desktop app, could you please still consider adding them to your list?

**Comment by jawz101** [comment]
It looks like you've hit up some other list maintainers as well that might be more suited for desktop software.  They seem reasonable but I'm trying to stick with mobile stuff.


You may want to reach out to a list like MVPS since it's really more Windows desktop type trackers and it's a popular base list for most big lists.


Or the yoyo blocklists

https://pgl.yoyo.org/adservers/

http://winhelp2002.mvps.org/hosts.htm


They should both have contact forms but if they get added to either of them it will trickle into the other combined lists you probably use.

**Comment by DRSDavidSoft** [comment]
@jawz101 Thank you, I'll try to see if these gets into any of these.
